name: CI

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: npm run build

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: npm run test

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint project files
        run: |
          npm run lint,
          npm run prettier:check
